---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Fail2Ban
- include_tasks: fail2ban-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'
    - security_fail2ban_enabled | bool

- include_tasks: fail2ban-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - security_fail2ban_enabled | bool

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes
  when: security_fail2ban_enabled | bool

# SSH
- include_tasks: ssh.yml
  when:
    - security_ssh_enabled | bool

# Autoupdate
- include_tasks: autoupdate-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'
    - security_autoupdate_enabled | bool

- include_tasks: autoupdate-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - security_autoupdate_enabled | bool
